myservice:
  image: myservice
  links:
    - rabbitmq
    - consul
rabbitmq:
  image: rabbitmq
  ports:
    - "5672"
consul:
  image: progrium/consul
  ports:
    - "8500"
  command: "-client 0.0.0.0 -config-dir /tmp"
sync:
  image: n3llyb0y/wait
  links:
    - rabbitmq
    - consul
  environment:
    PORTS: "5672 8500"
