version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - rabbitmq
      - consul
    environment:
      TARGETS: "rabbitmq:5672 consul:8500"
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  myservice:
    image: myservice

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  consul:
    image: progrium/consul
    ports:
      - "8500"
    command: "-client 0.0.0.0 -config-dir /tmp"
