version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - rabbitmq
    environment:
      TARGETS: "rabbitmq:5672"
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  myservice:
    image: myservice

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
